### ISSUE TITLE
Problem to add CSS file from controller when using absRefPrefix

### ISSUE THREAD

**Issue by sascha-seyfert** [mindshape-GmbH/mindshape_cookie_hint#1]
Hi, 

for my TYPO3 project I use the TS-Config "config.absRefPrefix = /mysubpage/".
But the including of the CSS-File is relative to the root-folder. 

I will make a Pull-Request to fix that.

**Comment by featdd** [comment]
Hi,

sorry for the late response, It will make more sense to add the css over typoscript.
Issue will be continued in #5
