### ISSUE TITLE
_LOCAL_LANG Changes not work in 1.0.12

### ISSUE THREAD

**Issue by afineske** [mindshape-GmbH/mindshape_cookie_hint#10]
`_LOCAL_LANG.de {
        hint.learnMore = Weitere Informationen.
        hint.dismiss = OK
        hint.message = Diese Webseite verwendet Cookies, um die Bedienfreundlichkeit zu erhöhen.
  }

  _LOCAL_LANG.default {
        hint.learnMore = More info.
        hint.dismiss = Got it
        hint.message = This website uses cookies to ensure you get the best experience on our website.
  }`
If i change i don't work.

**Comment by TrueType** [comment]
totally agree ;)

**Comment by featdd** [comment]
there are some issues, also mentioned in #9 
I'll have to excuse myself and begin to prepare a regression update right now.

**Comment by featdd** [comment]
I will push a regression update now, I reverted the last changes in 693c9e691767f42a5498d59f847c0c96b070e6de which should solve this issues by now.

sorry for any 693c9e691767f42a5498d59f847c0c96b070e6de
