### ISSUE TITLE
Page uid of the privacy policy should be text (is currently boolean)

### ISSUE THREAD

**Issue by cmichael-de** [mindshape-GmbH/mindshape_cookie_hint#11]
I changed locally on my website:
From # cat=mindshape_cookie_hint/settings; type=boolean; label=Page uid of the privacy policy
To: # cat=mindshape_cookie_hint/settings; type=text; label=Page uid of the privacy policy

After that I was able to edit a Page uid of the privacy policy.

**Comment by featdd** [comment]
boolean is of course wrong for the constant editor, but also text.
This has to be int, but thanks for the hint.

By the way you're still able to set the constant or setting manually :-)

Greetings
Daniel

**Comment by featdd** [comment]
solved in b91623cbedd3ee444c7d22f5690709c90e0bdbb6

**Comment by cmichael-de** [comment]
int ... yes, makes more sence than text! Thanks a lot!
