### ISSUE TITLE
body add class=cookie-padding 

### ISSUE THREAD

**Issue by ingeniumdesign** [mindshape-GmbH/mindshape_cookie_hint#12]
Hi,

the body class="cookie-padding" is perfect, but after the accepting from the Cookie-Warning, the class it´s the same.
Maybe you can hidden the class? Or a other class after the accepting from the Cookie.

`if (this.options.appendToBottom) {
                window.addEventListener("load", function () {
                    document.body.classList.add("cookie-padding");
                });
            }`

Thanks

**Comment by ingeniumdesign** [comment]
new Infos?

**Comment by featdd** [comment]
Hi, sorry for the late answer, I'll take a look at in the next time.
The class should be removable after accepting I guess.

Greetings
Daniel

**Comment by featdd** [comment]
@ingeniumdesign how did you configure your plugin?

I have set appendToBottom in the constant, but after accepting or reloading the page the class didn't show up anymore?

**Comment by ingeniumdesign** [comment]
hi, in the mindshape_cookie_hint | 1.0.14 there hold the class in body "cookie-padding"

**Comment by featdd** [comment]
@ingeniumdesign as mentioned in my last comment I couldn't reproduce this or what do you mean?

**Comment by featdd** [comment]
Closing this for no response
