### ISSUE TITLE
invalid HTML on 6.2

### ISSUE THREAD

**Issue by manuelLink** [mindshape-GmbH/mindshape_cookie_hint#13]
starting with version 1.0.10 the Extension does not create valid HTML code in TYPO3 6.2.
This is due to the new namespaces used in Resources/Private/Templates/Main/Cookie.html, which create an extra HTML-tag in 6.2

**Comment by featdd** [comment]
Could not reproduce this behaviour, and this TYPO3 version is not supported anymore.
