### ISSUE TITLE
css line height

### ISSUE THREAD

**Issue by DavidBruchmann** [mindshape-GmbH/mindshape_cookie_hint#15]
In the css-files is this snippet:
```
@media screen and (min-width: 768px) {
  .cc_container .cc_btn {
    font-size: 0.8em;
  }
  .cc_container .cc_message {
    font-size: 0.8em;
    line-height: 0.8em;
  }
}
```
The line `line-height: 0.8em;` in my opinion is not useful and provoking an ugly squeezed display.  
I changed it to `line-height: 1.5em;` by another CSS-file and think its much better readable and looking nicer too.  
As it's with `em`, it's always relative to the current font-size and never has to be changed if the font-size is changed,

**Comment by tobibuenter** [comment]
Exactly what I did yesterday...

**Comment by DavidBruchmann** [comment]
@featdd is there a reason why this issue never made it in the new release?

**Comment by featdd** [comment]
rel: https://github.com/mindshape-GmbH/mindshape_cookie_hint/issues/18#issuecomment-724638391
