### ISSUE TITLE
Release for v10 compatibility?

### ISSUE THREAD

**Issue by bmack** [mindshape-GmbH/mindshape_cookie_hint#18]
Hey,

thanks for your extension, I jumped in on a website project and found this extension in use, which is really. I'd love to update the website to TYPO3 v10, and it seems like you've already done most of the work to make this extension compatible. Any chances of having a new release in TER + on packagist with TYPO3 v10 compatibility?

Thanks.
Benni.

**Comment by featdd** [comment]
Hi @bmack,

thanks for your interest.

The plan is to deprecate this extension as it is not suitable for the current needs in comformity to the law.
We began making some adjustments to have it compatible but then started a completely new extension which I would recommend to you: [mindshape_cookie_consent](https://extensions.typo3.org/extension/mindshape_cookie_consent/)

Anyway, we're currently reviewing if it makes sense to push a last update before finally deprecating this extension.
I can tell you more next week.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @bmack @DavidBruchmann,

I just released the update v1.1.0 with compatibility for TYPO3 10.4.

Greetings
Daniel

**Comment by bmack** [comment]
🙇  thank you!

**Comment by DavidBruchmann** [comment]
Thank you, also for the hint about your other extension that is fulfilling today's needs better!
