### ISSUE TITLE
Problem to change templateRootPath

### ISSUE THREAD

**Issue by sstenz** [mindshape-GmbH/mindshape_cookie_hint#6]
Hi,

I have problems changing the templateRootPath. If I change this in the constants or in the setup, it has no effect.

Am I doing something wrong?

Thanks for the help!

**Comment by featdd** [comment]
Hi,

how did you set the path?

**Comment by sstenz** [comment]
Hi,

like this:
`plugin.tx_mindshapecookiehint.view.templateRootPath =  EXT:*my_provider-extension*/Resources/Private/Templates/`

If I have a look at the template with the Typoscript Object Browser I can see that my settings overwrite the default settings, but it still won't use my template.

**Comment by featdd** [comment]
Hi @sstenz,

this should solve your problem aae64e7da4d9f470753e9b081915acd9f6a2ce52, could you test this?

**Comment by sstenz** [comment]
Yeah! That was it!

Thanks a lot!
