### ISSUE TITLE
1.0.12 - massive breaking changes...

### ISSUE THREAD

**Issue by bernhardberger** [mindshape-GmbH/mindshape_cookie_hint#9]
Hi,

1.0.12 introduces a massive regressions due to the absence of the plugin. Every page where the EXT is configured manually via:

```typoscript
30 = USER
30 {
        userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
        pluginName = Main
        extensionName = MindshapeCookieHint
        vendorName = Mindshape
        action = cookie
        view < plugin.tx_mindshapecookiehint.view
        persistence < plugin.tx_mindshapecookiehint.persistence
    }
```

WILL break.

Please fix this regression and release a 1.0.13 and introduce breaking changes in a 2.0 version. This breaks any sane update policy and version constraints I'm afraid :/

**Comment by featdd** [comment]
You're right and I'm ashamed of myself, will prepare a regression update now.
The next "minor" version will be tested more properly and documented

**Comment by featdd** [comment]
I will push a regression update to ter, sorry for any inconveniences.
